name: pyMbseMdo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - pandas
  - pytest
  - scipy
  - seaborn
  - ca-certificates
  - numpy
  - h5py
  - plotly
  - sympy
  - jupyter
  - ipywidgets
  - pip:
      - openmdao
      - pyxdsm
      - casadi
      - pint
      - networkx
      - -e git+https://github.com/MariusLRuh/lsdo_atmos.git#egg=lsdo_atmos
      - -e git+https://github.com/LSDOlab/csdl.git@master#egg=csdl
      - -e git+https://github.com/LSDOlab/csdl_om.git@master#egg=csdl_om
      - -e git+https://github.com/LSDOlab/python_csdl_backend.git@master#egg=python_csdl_backend
      - -e git+https://github.com/anugrahjo/array_manager.git@modopt#egg=array_manager
      - -e git+https://github.com/LSDOlab/modopt.git#egg=modopt
      - -e git+https://github.com/jiy352/lsdo_VLM.git@caddee_branch#egg=VLM_package
